//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlaylistBuilder.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicPlaylistBuilder.Ressources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation state ({0}): {1}.
        /// </summary>
        internal static string ActivationState {
            get {
                return ResourceManager.GetString("ActivationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The AT9 ressources has been disposed..
        /// </summary>
        internal static string At9PlayerResourceReleased {
            get {
                return ResourceManager.GetString("At9PlayerResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &apos;audioFile&apos; resource has been released..
        /// </summary>
        internal static string AudioFileResourceReleased {
            get {
                return ResourceManager.GetString("AudioFileResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The audio file path cannot be null or empty..
        /// </summary>
        internal static string AudioPathNullOrEmpty {
            get {
                return ResourceManager.GetString("AudioPathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The BRSTM ressources has been disposed..
        /// </summary>
        internal static string BrstmPlayerResourceReleased {
            get {
                return ResourceManager.GetString("BrstmPlayerResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OOBEMusic.exe cannot be run in console mode..
        /// </summary>
        internal static string CannotRunInConsoleMode {
            get {
                return ResourceManager.GetString("CannotRunInConsoleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critical error in HookIntoWWA: {0}.
        /// </summary>
        internal static string CriticalErrorInHookIntoWWA {
            get {
                return ResourceManager.GetString("CriticalErrorInHookIntoWWA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t log in event viewer because of an error. Error code : {0}.
        /// </summary>
        internal static string ErrorCantLogInEventViewer {
            get {
                return ResourceManager.GetString("ErrorCantLogInEventViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while opening the AT9 file: {0}.
        /// </summary>
        internal static string ErrorOpeningAt9File {
            get {
                return ResourceManager.GetString("ErrorOpeningAt9File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while opening the BRSTM file: {0}.
        /// </summary>
        internal static string ErrorOpeningBrstmFile {
            get {
                return ResourceManager.GetString("ErrorOpeningBrstmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error releasing audio resources: {0}.
        /// </summary>
        internal static string ErrorReleasingAudioResources {
            get {
                return ResourceManager.GetString("ErrorReleasingAudioResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while stopping audio playback: {0}.
        /// </summary>
        internal static string ErrorStoppingAudioPlayback {
            get {
                return ResourceManager.GetString("ErrorStoppingAudioPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while stopping audio playback: {0}.
        /// </summary>
        internal static string ErrorStoppingAudioPlaybackNAudio {
            get {
                return ResourceManager.GetString("ErrorStoppingAudioPlaybackNAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file specified doesn&apos;t exist..
        /// </summary>
        internal static string FileDoesntExist {
            get {
                return ResourceManager.GetString("FileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified AT9 file could not be found..
        /// </summary>
        internal static string FileNotFoundAt9 {
            get {
                return ResourceManager.GetString("FileNotFoundAt9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified BRSTM file could not be found..
        /// </summary>
        internal static string FileNotFoundBrstm {
            get {
                return ResourceManager.GetString("FileNotFoundBrstm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key already exists (location of music file): {0}.
        /// </summary>
        internal static string KeyAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("KeyAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key does not exist, unable to verify activation state, the program will be activated by default..
        /// </summary>
        internal static string KeyNotFoundForActivation {
            get {
                return ResourceManager.GetString("KeyNotFoundForActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The registry key for the music file was not found. Using the default path..
        /// </summary>
        internal static string KeyNotFoundForMusicFile {
            get {
                return ResourceManager.GetString("KeyNotFoundForMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The registry key for the thread timeout was not found. Using the default value..
        /// </summary>
        internal static string KeyNotFoundForThreadTimeout {
            get {
                return ResourceManager.GetString("KeyNotFoundForThreadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key does not exist, creating it..
        /// </summary>
        internal static string KeyNotFoundMessage {
            get {
                return ResourceManager.GetString("KeyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The memory stream cannot be null..
        /// </summary>
        internal static string MemoryStreamNull {
            get {
                return ResourceManager.GetString("MemoryStreamNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error is preventing the music file to be played. Error code : {0}.
        /// </summary>
        internal static string MusicCrash {
            get {
                return ResourceManager.GetString("MusicCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred in the application preventing the music from playing. Check that the file is a .wav file and that the location specified in the Windows registry at the key HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\DestrClank\OOBEMusic\MusicFile points to a valid file location and that the file exists and is accessible. \nError code: {0}.
        /// </summary>
        internal static string MusicError {
            get {
                return ResourceManager.GetString("MusicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à naaaahhhh it doesn&apos;t work anymore: {0} In serious language: An error occurred in the application preventing the music from playing. Check that the file is a .wav file and that the location specified in the Windows registry at the key HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\DestrClank\OOBEMusic\MusicFile points to a valid file location and that the file exists and is accessible. Error code: {0}.
        /// </summary>
        internal static string MusicErrorVerbose {
            get {
                return ResourceManager.GetString("MusicErrorVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} process has been detected and the program is playing the music.\nFile location: {1}.
        /// </summary>
        internal static string MusicPlayed {
            get {
                return ResourceManager.GetString("MusicPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The music has been played, normally OnO.\nIn serious language: The {0} has been detected and the program is playing the music.\nFile location: {1}.
        /// </summary>
        internal static string MusicPlayedVerbose {
            get {
                return ResourceManager.GetString("MusicPlayedVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} process has been closed, the music will stop..
        /// </summary>
        internal static string MusicStopped {
            get {
                return ResourceManager.GetString("MusicStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The music has stopped, normally it&apos;s stopped.\nIn serious language: The {0} process has been closed, the music will stop..
        /// </summary>
        internal static string MusicStoppedVerbose {
            get {
                return ResourceManager.GetString("MusicStoppedVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &apos;NAudio&apos; resource has been released..
        /// </summary>
        internal static string NAudioResourceReleased {
            get {
                return ResourceManager.GetString("NAudioResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The At9Player object has already been disposed..
        /// </summary>
        internal static string ObjectDisposedAt9Player {
            get {
                return ResourceManager.GetString("ObjectDisposedAt9Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The BrstmPlayer object has already been disposed..
        /// </summary>
        internal static string ObjectDisposedBrstmPlayer {
            get {
                return ResourceManager.GetString("ObjectDisposedBrstmPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The NAudioClass object has already been disposed..
        /// </summary>
        internal static string ObjectDisposedNAudio {
            get {
                return ResourceManager.GetString("ObjectDisposedNAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SoundPlayerClass object has already been disposed..
        /// </summary>
        internal static string ObjectDisposedSoundPlayer {
            get {
                return ResourceManager.GetString("ObjectDisposedSoundPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &apos;outputDevice&apos; resource has been released..
        /// </summary>
        internal static string OutputDeviceResourceReleased {
            get {
                return ResourceManager.GetString("OutputDeviceResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The registry key has been created..
        /// </summary>
        internal static string RegistryCreatedMessage {
            get {
                return ResourceManager.GetString("RegistryCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while creating the registry key. \n Error code: {0}.
        /// </summary>
        internal static string RegistryCreationError {
            get {
                return ResourceManager.GetString("RegistryCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The registry key &apos;MusicFile&apos; has been successfully created..
        /// </summary>
        internal static string RegistryKeyCreatedMessage {
            get {
                return ResourceManager.GetString("RegistryKeyCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while creating the registry key &apos;MusicFile&apos;. Error: {0}.
        /// </summary>
        internal static string RegistryKeyCreationError {
            get {
                return ResourceManager.GetString("RegistryKeyCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plays music during the Microsoft Out-of-Box Experience..
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service running in interactive debugging mode..
        /// </summary>
        internal static string ServiceInteractiveDebugMode {
            get {
                return ResourceManager.GetString("ServiceInteractiveDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation error: {0}.
        /// </summary>
        internal static string ServiceOperationError {
            get {
                return ResourceManager.GetString("ServiceOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The OOBEMusic.exe service has started successfully..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service has been installed and started successfully..
        /// </summary>
        internal static string ServiceStartedUponInstall {
            get {
                return ResourceManager.GetString("ServiceStartedUponInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à uiiiii it works In serious language: The OOBEMusic.exe service has started successfully..
        /// </summary>
        internal static string ServiceStartedVerbose {
            get {
                return ResourceManager.GetString("ServiceStartedVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service didn&apos;t start properly after installation : Error code {0}.
        /// </summary>
        internal static string ServiceStartError {
            get {
                return ResourceManager.GetString("ServiceStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Values {0}, {1} and {2} are not set to 1. The program will stop..
        /// </summary>
        internal static string ServiceStoppedBothKeysInactive {
            get {
                return ResourceManager.GetString("ServiceStoppedBothKeysInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The process received a system stop request. The process will stop..
        /// </summary>
        internal static string ServiceStopRequest {
            get {
                return ResourceManager.GetString("ServiceStopRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nope: In serious language: The process received a system stop request. The process will stop..
        /// </summary>
        internal static string ServiceStopRequestVerbose {
            get {
                return ResourceManager.GetString("ServiceStopRequestVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service did not start in the allotted time: {0}.
        /// </summary>
        internal static string ServiceTimeoutError {
            get {
                return ResourceManager.GetString("ServiceTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error: {0}.
        /// </summary>
        internal static string ServiceUnexpectedError {
            get {
                return ResourceManager.GetString("ServiceUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The service has not been uninstalled properly. Error code : {0}.
        /// </summary>
        internal static string ServiceUninstallError {
            get {
                return ResourceManager.GetString("ServiceUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &apos;SoundPlayer&apos; resource has been released..
        /// </summary>
        internal static string SoundPlayerResourceReleased {
            get {
                return ResourceManager.GetString("SoundPlayerResourceReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The thread timeout value is too low. Adjusted to the minimum allowed value: {0} ms..
        /// </summary>
        internal static string ThreadTimeoutTooLow {
            get {
                return ResourceManager.GetString("ThreadTimeoutTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The thread timeout value is set to: {0} ms..
        /// </summary>
        internal static string ThreadTimeoutValue {
            get {
                return ResourceManager.GetString("ThreadTimeoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value {0} does not exist..
        /// </summary>
        internal static string ValueNotFound {
            get {
                return ResourceManager.GetString("ValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value {0} does not exist, the program will activate by default..
        /// </summary>
        internal static string ValueNotFoundDefaultActivation {
            get {
                return ResourceManager.GetString("ValueNotFoundDefaultActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value for the thread timeout was not found. Using the default value: {0} ms..
        /// </summary>
        internal static string ValueNotFoundDefaultThreadTimeout {
            get {
                return ResourceManager.GetString("ValueNotFoundDefaultThreadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type of the value {0} is not convertible to Integer.\n Error code: {1}.
        /// </summary>
        internal static string ValueTypeError {
            get {
                return ResourceManager.GetString("ValueTypeError", resourceCulture);
            }
        }
    }
}
